### PR TITLE
support DINERS_CLUB and JCB

### PR DESCRIPTION
**Pull request by Eklett**
Now supported DINERS_CLUB and JCB. 
TODO support JCB cards which is beginning with 2131 or 1800.
I do not have jcb.png icon , so it need to change the same size of this icon with others.

### CODE REVIEW

**Comment by dbachelder** [comment]
Thanks for the PR! The card icons need to match the size and style of the ones the library uses. 

We need to find someone to restyle all the fronts and backs to be consistent. I'll do some searching to see if I can find some existing resources or someone to create them.

**Comment by josefdlange** [comment]
Might want to look into utilizing an icon font like [FontAwesome](http://fontawesome.io) to do the icons. Coupled with [Android-Iconify](https://github.com/JoanZapata/android-iconify) you'll have a pretty good experience. That being said I do wonder the impact of the transitive dependency. Maybe you can "borrow" some of the code from Iconify to at least load an icon font and extract the icons. Or, even download the FontAwesome raw resources to have new consistent icons.

Anyway, just my $0.02...

**Comment by perryao** [comment]
what else needs to be done to get this merged?

**Comment by dbachelder** [comment]
it needs to be rebased and it needs to have the icons fixed. ideally it wouldn't have all the reformatting so the diff would just be for the things that actually changed to support this use case...  (we can fix the bad formatting in another PR)

**Comment by skywall** [comment]
Shouldn't this be closed because of actual support mentioned card types?

**Pull request closed without merging**
