### PR TITLE
Zipcode textwatcher

### PR DESCRIPTION
**Pull request by zafrani**
Need this for zip codes in other countries that have different lengths.

### CODE REVIEW

**Comment by zafrani** [comment]
@dbachelder Would it be possible to merge this? We want to include the project with our build for our next release.

**Comment by dbachelder** [comment]
Hey @zafrani. Thanks for the PR... could you add an entry to the readme and squash into a single commit?

**Comment by dbachelder** [comment]
@zafrani still interested in merging this?

**Comment by zafrani** [comment]
@dbachelder Yeah sorry was held up the other day. Everything's ready.

**Comment by dbachelder** [comment]
Ok, it's merged and 1.4.7 is released! thanks.

**Comment by zafrani** [comment]
Thank you

**Pull request merged**
